include $(GNUSTEP_MAKEFILES)/common.make

DOCUMENT_NAME = manual

manual_LATEX_FILES = \
manual.tex \
title.tex \
autolayout.tex \
gsmarkup.tex

SUBPROJECTS = Tutorials

include $(GNUSTEP_MAKEFILES)/documentation.make
include $(GNUSTEP_MAKEFILES)/aggregate.make
